### ISSUE TITLE
Feature request: adjust target colors for IR cameras

### ISSUE THREAD

**Issue by etymotic** [tangentaudio/opencv_tank_gauge#3]
I have an IR camera (no IR filter and IR lights that are always on) which is black/white, maybe a pinkish hue. I'm able to get this project working, but only if I shine a bright light directly on the gauge.

It detects the line segments easily (they come across as black), but the float is white with just the IR lights.

Is there a way to have it look for shades of white as opposed to shades of red?

I looked through gauge.py and found the following lines which I might be able to adjust:

```
ind_lower_red = np.array([145,112,0])
ind_upper_red = np.array([179,255,255])
```
I'm not sure what the values would be once converted to HSV.

Thanks.

**Comment by tangentaudio** [comment]
Hi @timnunes,
Since the IR camera is essentially black and white, it might take a different approach to detect the position of the indicator than the one I used to find red pixels.  I'm not sure an HSV range will work well.

A good first step would be to get an unprocessed image from your setup.  Easiest thing to do would be to stop the gauge-cv service via systemctl and then run `raspistill --width 800 --height 608 --encoding png --output test.png` 

Once you've got test.png, you can drop it into a comment here, e.g.:

![test](https://user-images.githubusercontent.com/3910098/202522884-cf09fccd-ea41-4a17-9f28-a108e7d87356.png)

**Comment by etymotic** [comment]
Thanks for the reply.

First a picture with the just the built in IR lights:
![test](https://user-images.githubusercontent.com/35511093/202525272-a2c1d8a2-1c13-4713-b1e7-3db220c0cd06.png)

Next is a picture with a lamp shining directly on the gauge:
![test with light](https://user-images.githubusercontent.com/35511093/202525448-6b1fb1d2-79ad-46d3-b71d-ef2937001ee4.png)

For fun, a screenshot of the web app with the lamp turned OFF:
![no light](https://user-images.githubusercontent.com/35511093/202525725-c36ab147-9f4d-4182-a39e-b80973fdfd9f.png)

...and a screenshot of the web app with the lamp turned ON:
![lamp on](https://user-images.githubusercontent.com/35511093/202525792-4ca34055-fa69-4980-8e00-11349ffac8af.png)

**Comment by etymotic** [comment]
I may not be a smart man, but it seems that I have figured out how to adjust gauge.py to fit my needs. I'll add my edits below for anyone else looking. 

In summary, I commented out the line that converts to HSV, adjusted the HTML color codes to match my camera output, and changed the reference to "ind_crop_hsv" to "ind_crop", since I'm skipping the conversion to HSV.

Thanks @tangentaudio, not only for this really great project, but also for pointing me in the right direction.

```
        # find the red indicator with a mask and range
        #ind_crop_hsv = cv2.cvtColor(ind_crop, cv2.COLOR_BGR2HSV) (commented out so no conversion happens. Optional, since we remove reference to "ind_crop_hsv" further down)

        #use an online tool to find the html colors of the float indicator in your image and adjust accordingly
        ind_lower_red = np.array([183,130,204])
        ind_upper_red = np.array([255,255,255])

        #Changed the reference from "ind_crop_hsv" to "ind_crop".
        ind_red_mask = cv2.inRange(ind_crop, ind_lower_red, ind_upper_red)
```

**Comment by tangentaudio** [comment]
Glad to hear you got it working!  At some point I will make a round of improvements to the code and try to make it flexible enough to work with a setup like yours without code changes.  Cheers.
